version: "3.3"

services:
  db:
    image: postgres:13.3
    container_name: postgres_container
    environment:
      POSTGRES_DB: "crawler_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"

  docker-service:
    container_name: data-crawler-service_container
    image: 'docker-service:latest'
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - db
    links:
      - "db:database"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/crawler_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

